# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# .pre-commit-config.yaml

repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
